// <auto-generated />
namespace FireCaffeDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DB_INITIAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_INITIAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202103061119330_DB_INITIAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
